function export_voxel_to_stl_binary(voxel, stlFile, voxelSize)
% EXPORT_VOXEL_TO_STL_BINARY Export a logical voxel volume to binary STL.
%
% Robust direct voxel-face exporter.
% It does NOT use isosurface, stlwrite, padarray, or any toolbox-specific function.
% Each exposed voxel face is written as two triangles.

if nargin < 3 || isempty(voxelSize)
    voxelSize = [1 1 1];
end

voxel = logical(voxel);
if ~any(voxel(:))
    error('Voxel model is empty.');
end

[nx, ny, nz] = size(voxel);
dx = voxelSize(1);
dy = voxelSize(2);
dz = voxelSize(3);

[I, J, K] = ind2sub(size(voxel), find(voxel));
nActive = numel(I);

% ---------------- Count exposed faces first ----------------
faceCount = 0;
for n = 1:nActive
    i = I(n); j = J(n); k = K(n);

    if i == 1  || ~voxel(i-1,j,k); faceCount = faceCount + 1; end
    if i == nx || ~voxel(i+1,j,k); faceCount = faceCount + 1; end
    if j == 1  || ~voxel(i,j-1,k); faceCount = faceCount + 1; end
    if j == ny || ~voxel(i,j+1,k); faceCount = faceCount + 1; end
    if k == 1  || ~voxel(i,j,k-1); faceCount = faceCount + 1; end
    if k == nz || ~voxel(i,j,k+1); faceCount = faceCount + 1; end
end

triCount = uint32(faceCount * 2);

[fid, msg] = fopen(stlFile, 'wb');
if fid == -1
    error('Cannot open STL file for writing: %s | %s', stlFile, msg);
end
cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

% ---------------- Binary STL header ----------------
header = uint8(zeros(1, 80));
label = uint8('Voxel lattice STL generated by direct face exporter');
header(1:numel(label)) = label;
fwrite(fid, header, 'uint8');
fwrite(fid, triCount, 'uint32');

fprintf('Active voxels  : %d\n', nActive);
fprintf('Exposed faces  : %d\n', faceCount);
fprintf('STL triangles  : %d\n', double(triCount));

% ---------------- Write exposed faces ----------------
for n = 1:nActive
    i = I(n); j = J(n); k = K(n);

    x0 = (i-1) * dx; x1 = i * dx;
    y0 = (j-1) * dy; y1 = j * dy;
    z0 = (k-1) * dz; z1 = k * dz;

    % x-min face, normal [-1 0 0]
    if i == 1 || ~voxel(i-1,j,k)
        nrm = [-1 0 0];
        write_tri(fid, nrm, [x0 y0 z0], [x0 y0 z1], [x0 y1 z1]);
        write_tri(fid, nrm, [x0 y0 z0], [x0 y1 z1], [x0 y1 z0]);
    end

    % x-max face, normal [1 0 0]
    if i == nx || ~voxel(i+1,j,k)
        nrm = [1 0 0];
        write_tri(fid, nrm, [x1 y0 z0], [x1 y1 z1], [x1 y0 z1]);
        write_tri(fid, nrm, [x1 y0 z0], [x1 y1 z0], [x1 y1 z1]);
    end

    % y-min face, normal [0 -1 0]
    if j == 1 || ~voxel(i,j-1,k)
        nrm = [0 -1 0];
        write_tri(fid, nrm, [x0 y0 z0], [x1 y0 z1], [x0 y0 z1]);
        write_tri(fid, nrm, [x0 y0 z0], [x1 y0 z0], [x1 y0 z1]);
    end

    % y-max face, normal [0 1 0]
    if j == ny || ~voxel(i,j+1,k)
        nrm = [0 1 0];
        write_tri(fid, nrm, [x0 y1 z0], [x0 y1 z1], [x1 y1 z1]);
        write_tri(fid, nrm, [x0 y1 z0], [x1 y1 z1], [x1 y1 z0]);
    end

    % z-min face, normal [0 0 -1]
    if k == 1 || ~voxel(i,j,k-1)
        nrm = [0 0 -1];
        write_tri(fid, nrm, [x0 y0 z0], [x0 y1 z0], [x1 y1 z0]);
        write_tri(fid, nrm, [x0 y0 z0], [x1 y1 z0], [x1 y0 z0]);
    end

    % z-max face, normal [0 0 1]
    if k == nz || ~voxel(i,j,k+1)
        nrm = [0 0 1];
        write_tri(fid, nrm, [x0 y0 z1], [x1 y1 z1], [x0 y1 z1]);
        write_tri(fid, nrm, [x0 y0 z1], [x1 y0 z1], [x1 y1 z1]);
    end
end

end

function write_tri(fid, nrm, v1, v2, v3)
fwrite(fid, single(nrm), 'float32');
fwrite(fid, single(v1),  'float32');
fwrite(fid, single(v2),  'float32');
fwrite(fid, single(v3),  'float32');
fwrite(fid, uint16(0),   'uint16');
end
